import { CSSProperties, JSX } from 'react';

import { FontColor, BackgroundColor, BlockType, CodeLanguage } from '../type';

export const TextColorMap: Record<FontColor, CSSProperties['color']> = {
    [FontColor.Red]: 'red',
    [FontColor.Orange]: 'orange',
    [FontColor.Yellow]: 'yellow',
    [FontColor.Green]: 'green',
    [FontColor.Blue]: 'blue',
    [FontColor.Purple]: 'purple',
    [FontColor.Gray]: 'gray'
};

export const BackgroundColorMap: Record<BackgroundColor, CSSProperties['backgroundColor']> = {
    [BackgroundColor.LightRedBackground]: '#ffcccc',
    [BackgroundColor.LightOrangeBackground]: '#ffe6cc',
    [BackgroundColor.LightYellowBackground]: '#ffffcc',
    [BackgroundColor.LightGreenBackground]: '#e6ffe6',
    [BackgroundColor.LightBlueBackground]: '#cceeff',
    [BackgroundColor.LightPurpleBackground]: '#f2e6ff',
    [BackgroundColor.PaleGrayBackground]: '#f2f2f2',
    [BackgroundColor.DarkRedBackground]: 'red',
    [BackgroundColor.DarkOrangeBackground]: 'orange',
    [BackgroundColor.DarkYellowBackground]: 'yellow',
    [BackgroundColor.DarkGreenBackground]: 'green',
    [BackgroundColor.DarkBlueBackground]: 'blue',
    [BackgroundColor.DarkPurpleBackground]: 'purple',
    [BackgroundColor.DarkGrayBackground]: 'gray',
    [BackgroundColor.LightGrayBackground]: 'lightgray'
};

export const TextTagMap: Partial<Record<BlockType, keyof JSX.IntrinsicElements>> = {
    [BlockType.page]: 'article',
    [BlockType.text]: 'p',
    [BlockType.heading1]: 'h1',
    [BlockType.heading2]: 'h2',
    [BlockType.heading3]: 'h3',
    [BlockType.heading4]: 'h4',
    [BlockType.heading5]: 'h5',
    [BlockType.heading6]: 'h6',
    [BlockType.bullet]: 'ul',
    [BlockType.ordered]: 'ol',
    [BlockType.code]: 'pre',
    [BlockType.quote]: 'blockquote',
    [BlockType.todo]: 'div'
};

export const CodeLanguageMap: Record<CodeLanguage, string> = {
    [CodeLanguage.PlainText]: 'plaintext',
    [CodeLanguage.ABAP]: 'abap',
    [CodeLanguage.Ada]: 'ada',
    [CodeLanguage.Apache]: 'apache',
    [CodeLanguage.Apex]: 'apex',
    [CodeLanguage.Assembly]: 'assembly',
    [CodeLanguage.Bash]: 'bash',
    [CodeLanguage.CSharp]: 'csharp',
    [CodeLanguage.CPlusPlus]: 'cpp',
    [CodeLanguage.C]: 'c',
    [CodeLanguage.COBOL]: 'cobol',
    [CodeLanguage.CSS]: 'css',
    [CodeLanguage.CoffeeScript]: 'coffeescript',
    [CodeLanguage.D]: 'd',
    [CodeLanguage.Dart]: 'dart',
    [CodeLanguage.Delphi]: 'delphi',
    [CodeLanguage.Django]: 'django',
    [CodeLanguage.Dockerfile]: 'dockerfile',
    [CodeLanguage.Erlang]: 'erlang',
    [CodeLanguage.Fortran]: 'fortran',
    [CodeLanguage.FoxPro]: 'foxpro',
    [CodeLanguage.Go]: 'go',
    [CodeLanguage.Groovy]: 'groovy',
    [CodeLanguage.HTML]: 'html',
    [CodeLanguage.HTMLBars]: 'htmlbars',
    [CodeLanguage.HTTP]: 'http',
    [CodeLanguage.Haskell]: 'haskell',
    [CodeLanguage.JSON]: 'json',
    [CodeLanguage.Java]: 'java',
    [CodeLanguage.JavaScript]: 'javascript',
    [CodeLanguage.Julia]: 'julia',
    [CodeLanguage.Kotlin]: 'kotlin',
    [CodeLanguage.LateX]: 'latex',
    [CodeLanguage.Lisp]: 'lisp',
    [CodeLanguage.Logo]: 'logo',
    [CodeLanguage.Lua]: 'lua',
    [CodeLanguage.MATLAB]: 'matlab',
    [CodeLanguage.Makefile]: 'makefile',
    [CodeLanguage.Markdown]: 'markdown',
    [CodeLanguage.Nginx]: 'nginx',
    [CodeLanguage.Objective]: 'objective-c',
    [CodeLanguage.OpenEdgeABL]: 'openedge-abl',
    [CodeLanguage.PHP]: 'php',
    [CodeLanguage.Perl]: 'perl',
    [CodeLanguage.PostScript]: 'postscript',
    [CodeLanguage.PowerShell]: 'powershell',
    [CodeLanguage.Prolog]: 'prolog',
    [CodeLanguage.ProtoBuf]: 'protobuf',
    [CodeLanguage.Python]: 'python',
    [CodeLanguage.R]: 'r',
    [CodeLanguage.RPG]: 'rpg',
    [CodeLanguage.Ruby]: 'ruby',
    [CodeLanguage.Rust]: 'rust',
    [CodeLanguage.SAS]: 'sas',
    [CodeLanguage.SCSS]: 'scss',
    [CodeLanguage.SQL]: 'sql',
    [CodeLanguage.Scala]: 'scala',
    [CodeLanguage.Scheme]: 'scheme',
    [CodeLanguage.Scratch]: 'scratch',
    [CodeLanguage.Shell]: 'shell',
    [CodeLanguage.Swift]: 'swift',
    [CodeLanguage.Thrift]: 'thrift',
    [CodeLanguage.TypeScript]: 'typescript',
    [CodeLanguage.VBScript]: 'vbscript',
    [CodeLanguage.Visual]: 'visual',
    [CodeLanguage.XML]: 'xml',
    [CodeLanguage.YAML]: 'yaml',
    [CodeLanguage.CMake]: 'cmake',
    [CodeLanguage.Diff]: 'diff',
    [CodeLanguage.Gherkin]: 'gherkin',
    [CodeLanguage.GraphQL]: 'graphql',
    [CodeLanguage.OpenGL_Shading_Language]: 'glsl',
    [CodeLanguage.Properties]: 'properties',
    [CodeLanguage.Solidity]: 'solidity',
    [CodeLanguage.TOML]: 'toml'
};
